# Generated by Django 6.0.6 on 2026-06-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEMBRE', 'Membre'), ('ACHETEUR', 'Acheteur'), ('FORMATEUR', 'Formateur'), ('LIVREUR', 'Livreur')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('adresse_livraison', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('specialite', models.CharField(max_length=100)),
                ('biographie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('vehicule', models.CharField(max_length=50)),
                ('zone_couverture', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('fonction', models.CharField(max_length=80)),
                ('niveau_acces', models.CharField(max_length=20)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('numero_adhesion', models.CharField(max_length=30)),
                ('date_adhesion', models.DateField()),
                ('statut_cotisation', models.BooleanField(default=False)),
                ('montant_cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.cooperative')),
            ],
        ),
    ]
