# Generated by Django 5.2.15 on 2026-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrateur",
            name="niveau_acces",
            field=models.CharField(
                choices=[
                    ("LECTURE", "Lecture seule"),
                    ("GESTION", "Gestion"),
                    ("TOTAL", "Accès total"),
                ],
                default="GESTION",
                max_length=20,
            ),
        ),
    ]
