# Generated by Django 5.2.15 on 2026-06-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_administrateur_niveau_acces"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acheteur",
            options={"verbose_name": "Acheteur", "verbose_name_plural": "Acheteurs"},
        ),
        migrations.AlterModelOptions(
            name="administrateur",
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="formateur",
            options={"verbose_name": "Formateur", "verbose_name_plural": "Formateurs"},
        ),
        migrations.AlterModelOptions(
            name="livreur",
            options={"verbose_name": "Livreur", "verbose_name_plural": "Livreurs"},
        ),
        migrations.AlterModelOptions(
            name="membre",
            options={"verbose_name": "Membre", "verbose_name_plural": "Membres"},
        ),
    ]
