-- =====================================================================
-- Plateforme de Gestion des Coopératives Agricoles
-- Script SQL de création de la base de données (PostgreSQL)
-- Université Virtuelle du Burkina Faso - Licence 3 - 2025-2026
--
-- Ce script crée l'intégralité du schéma relationnel : tables métier
-- (utilisateurs, coopératives, productions, produits, commandes,
-- paiements, reçus, livraisons, formations, quiz, suivis) ainsi que
-- les tables internes de Django (sessions, permissions, migrations).
--
-- Utilisation :
--   createdb -U postgres coop_platform
--   psql -U postgres -d coop_platform -f schema.sql
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: formation_formation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.formation_formation (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    type_contenu character varying(20) NOT NULL,
    contenu text,
    duree_estimee character varying(50) NOT NULL,
    statut character varying(50) NOT NULL,
    formateur_id bigint NOT NULL
);


--
-- Name: formation_formation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.formation_formation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formation_formation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: formation_quiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.formation_quiz (
    id bigint NOT NULL,
    question text NOT NULL,
    choix_a character varying(255) NOT NULL,
    choix_b character varying(255) NOT NULL,
    choix_c character varying(255) NOT NULL,
    bonne_reponse character varying(1) NOT NULL,
    formation_id bigint NOT NULL
);


--
-- Name: formation_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.formation_quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formation_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: formation_suiviformation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.formation_suiviformation (
    id bigint NOT NULL,
    progression numeric(10,2) NOT NULL,
    score_quiz integer NOT NULL,
    statut character varying(20) NOT NULL,
    formation_id bigint NOT NULL,
    membre_id bigint NOT NULL
);


--
-- Name: formation_suiviformation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.formation_suiviformation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formation_suiviformation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productions_cooperative; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productions_cooperative (
    id bigint NOT NULL,
    nom character varying(150) NOT NULL,
    description text,
    localisation character varying(150) NOT NULL,
    date_creation date NOT NULL,
    statut character varying(50) NOT NULL,
    createur_id bigint
);


--
-- Name: productions_cooperative_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productions_cooperative ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productions_cooperative_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productions_production; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productions_production (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    type_culture character varying(80) NOT NULL,
    quantite numeric(10,2) NOT NULL,
    unite character varying(30) NOT NULL,
    date_recolte date NOT NULL,
    statut_validation boolean NOT NULL,
    membre_id bigint NOT NULL
);


--
-- Name: productions_production_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productions_production ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productions_production_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productions_produit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productions_produit (
    id bigint NOT NULL,
    nom character varying(150) NOT NULL,
    description text,
    prix_unitaire numeric(10,2) NOT NULL,
    quantite_stock integer NOT NULL,
    diponible boolean NOT NULL,
    image character varying(100),
    production_id bigint NOT NULL
);


--
-- Name: productions_produit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productions_produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productions_produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_commande; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_commande (
    id bigint NOT NULL,
    reference character varying(30) NOT NULL,
    date_commande timestamp with time zone NOT NULL,
    montant_total numeric(10,2) NOT NULL,
    statut character varying(50) NOT NULL,
    acheteur_id bigint NOT NULL
);


--
-- Name: sales_commande_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_commande ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_commande_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_lignecommande; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_lignecommande (
    id bigint NOT NULL,
    quantite integer NOT NULL,
    prix_unitaire numeric(10,2) NOT NULL,
    sous_total numeric(10,2) NOT NULL,
    commande_id bigint NOT NULL,
    produit_id bigint NOT NULL
);


--
-- Name: sales_lignecommande_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_lignecommande ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_lignecommande_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_livraison; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_livraison (
    id bigint NOT NULL,
    adresse_livraison character varying(255) NOT NULL,
    date_livraison timestamp with time zone,
    statut character varying(50) NOT NULL,
    commande_id bigint NOT NULL,
    livreur_id bigint NOT NULL
);


--
-- Name: sales_livraison_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_livraison ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_livraison_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_paiement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_paiement (
    id bigint NOT NULL,
    montant numeric(10,2) NOT NULL,
    methode character varying(50) NOT NULL,
    statut character varying(50) NOT NULL,
    date_paiement timestamp with time zone NOT NULL,
    reference_transaction character varying(100) NOT NULL,
    commande_id bigint NOT NULL
);


--
-- Name: sales_paiement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_paiement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_paiement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_recu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_recu (
    id bigint NOT NULL,
    numero character varying(50) NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    montant numeric(10,2) NOT NULL,
    paiement_id bigint NOT NULL
);


--
-- Name: sales_recu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_recu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_recu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_acheteur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_acheteur (
    utilisateur_id bigint NOT NULL,
    adresse_livraison character varying(200) NOT NULL
);


--
-- Name: users_administrateur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_administrateur (
    utilisateur_id bigint NOT NULL,
    fonction character varying(80) NOT NULL,
    niveau_acces character varying(20) NOT NULL,
    cooperative_id bigint NOT NULL
);


--
-- Name: users_formateur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_formateur (
    utilisateur_id bigint NOT NULL,
    specialite character varying(100) NOT NULL,
    biographie text NOT NULL
);


--
-- Name: users_livreur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_livreur (
    utilisateur_id bigint NOT NULL,
    vehicule character varying(50) NOT NULL,
    zone_couverture character varying(100) NOT NULL,
    disponible boolean NOT NULL
);


--
-- Name: users_membre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_membre (
    utilisateur_id bigint NOT NULL,
    numero_adhesion character varying(30) NOT NULL,
    date_adhesion date NOT NULL,
    statut_cotisation boolean NOT NULL,
    montant_cotisation numeric(10,2) NOT NULL,
    cooperative_id bigint NOT NULL
);


--
-- Name: users_utilisateur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_utilisateur (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    nom character varying(80) NOT NULL,
    prenom character varying(80) NOT NULL,
    email character varying(254) NOT NULL,
    telephone character varying(50) NOT NULL,
    adresse character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_inscription timestamp with time zone NOT NULL
);


--
-- Name: users_utilisateur_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_utilisateur_groups (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_utilisateur_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_utilisateur_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_utilisateur_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_utilisateur_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_utilisateur_user_permissions (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_utilisateur_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_utilisateur_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_utilisateur_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: formation_formation formation_formation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_formation
    ADD CONSTRAINT formation_formation_pkey PRIMARY KEY (id);


--
-- Name: formation_quiz formation_quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_quiz
    ADD CONSTRAINT formation_quiz_pkey PRIMARY KEY (id);


--
-- Name: formation_suiviformation formation_suiviformation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_suiviformation
    ADD CONSTRAINT formation_suiviformation_pkey PRIMARY KEY (id);


--
-- Name: productions_cooperative productions_cooperative_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions_cooperative
    ADD CONSTRAINT productions_cooperative_pkey PRIMARY KEY (id);


--
-- Name: productions_production productions_production_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions_production
    ADD CONSTRAINT productions_production_pkey PRIMARY KEY (id);


--
-- Name: productions_produit productions_produit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions_produit
    ADD CONSTRAINT productions_produit_pkey PRIMARY KEY (id);


--
-- Name: sales_commande sales_commande_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commande
    ADD CONSTRAINT sales_commande_pkey PRIMARY KEY (id);


--
-- Name: sales_commande sales_commande_reference_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commande
    ADD CONSTRAINT sales_commande_reference_key UNIQUE (reference);


--
-- Name: sales_lignecommande sales_lignecommande_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_lignecommande
    ADD CONSTRAINT sales_lignecommande_pkey PRIMARY KEY (id);


--
-- Name: sales_livraison sales_livraison_commande_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_livraison
    ADD CONSTRAINT sales_livraison_commande_id_key UNIQUE (commande_id);


--
-- Name: sales_livraison sales_livraison_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_livraison
    ADD CONSTRAINT sales_livraison_pkey PRIMARY KEY (id);


--
-- Name: sales_paiement sales_paiement_commande_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_paiement
    ADD CONSTRAINT sales_paiement_commande_id_key UNIQUE (commande_id);


--
-- Name: sales_paiement sales_paiement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_paiement
    ADD CONSTRAINT sales_paiement_pkey PRIMARY KEY (id);


--
-- Name: sales_paiement sales_paiement_reference_transaction_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_paiement
    ADD CONSTRAINT sales_paiement_reference_transaction_key UNIQUE (reference_transaction);


--
-- Name: sales_recu sales_recu_numero_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_recu
    ADD CONSTRAINT sales_recu_numero_key UNIQUE (numero);


--
-- Name: sales_recu sales_recu_paiement_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_recu
    ADD CONSTRAINT sales_recu_paiement_id_key UNIQUE (paiement_id);


--
-- Name: sales_recu sales_recu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_recu
    ADD CONSTRAINT sales_recu_pkey PRIMARY KEY (id);


--
-- Name: users_acheteur users_acheteur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_acheteur
    ADD CONSTRAINT users_acheteur_pkey PRIMARY KEY (utilisateur_id);


--
-- Name: users_administrateur users_administrateur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_administrateur
    ADD CONSTRAINT users_administrateur_pkey PRIMARY KEY (utilisateur_id);


--
-- Name: users_formateur users_formateur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_formateur
    ADD CONSTRAINT users_formateur_pkey PRIMARY KEY (utilisateur_id);


--
-- Name: users_livreur users_livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_livreur
    ADD CONSTRAINT users_livreur_pkey PRIMARY KEY (utilisateur_id);


--
-- Name: users_membre users_membre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_membre
    ADD CONSTRAINT users_membre_pkey PRIMARY KEY (utilisateur_id);


--
-- Name: users_utilisateur users_utilisateur_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur
    ADD CONSTRAINT users_utilisateur_email_key UNIQUE (email);


--
-- Name: users_utilisateur_groups users_utilisateur_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_groups
    ADD CONSTRAINT users_utilisateur_groups_pkey PRIMARY KEY (id);


--
-- Name: users_utilisateur_groups users_utilisateur_groups_utilisateur_id_group_id_753c4b93_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_groups
    ADD CONSTRAINT users_utilisateur_groups_utilisateur_id_group_id_753c4b93_uniq UNIQUE (utilisateur_id, group_id);


--
-- Name: users_utilisateur users_utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur
    ADD CONSTRAINT users_utilisateur_pkey PRIMARY KEY (id);


--
-- Name: users_utilisateur_user_permissions users_utilisateur_user_p_utilisateur_id_permissio_76fca242_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_user_permissions
    ADD CONSTRAINT users_utilisateur_user_p_utilisateur_id_permissio_76fca242_uniq UNIQUE (utilisateur_id, permission_id);


--
-- Name: users_utilisateur_user_permissions users_utilisateur_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_user_permissions
    ADD CONSTRAINT users_utilisateur_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: formation_formation_formateur_id_1f68fbfc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX formation_formation_formateur_id_1f68fbfc ON public.formation_formation USING btree (formateur_id);


--
-- Name: formation_quiz_formation_id_1cc0355b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX formation_quiz_formation_id_1cc0355b ON public.formation_quiz USING btree (formation_id);


--
-- Name: formation_suiviformation_formation_id_36d05635; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX formation_suiviformation_formation_id_36d05635 ON public.formation_suiviformation USING btree (formation_id);


--
-- Name: formation_suiviformation_membre_id_8a583b12; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX formation_suiviformation_membre_id_8a583b12 ON public.formation_suiviformation USING btree (membre_id);


--
-- Name: productions_cooperative_createur_id_32e421e9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productions_cooperative_createur_id_32e421e9 ON public.productions_cooperative USING btree (createur_id);


--
-- Name: productions_production_membre_id_70298c95; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productions_production_membre_id_70298c95 ON public.productions_production USING btree (membre_id);


--
-- Name: productions_produit_production_id_3cf32b21; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productions_produit_production_id_3cf32b21 ON public.productions_produit USING btree (production_id);


--
-- Name: sales_commande_acheteur_id_452d3519; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_commande_acheteur_id_452d3519 ON public.sales_commande USING btree (acheteur_id);


--
-- Name: sales_commande_reference_3f39a0fd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_commande_reference_3f39a0fd_like ON public.sales_commande USING btree (reference varchar_pattern_ops);


--
-- Name: sales_lignecommande_commande_id_5ffb0313; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_lignecommande_commande_id_5ffb0313 ON public.sales_lignecommande USING btree (commande_id);


--
-- Name: sales_lignecommande_produit_id_780eeaac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_lignecommande_produit_id_780eeaac ON public.sales_lignecommande USING btree (produit_id);


--
-- Name: sales_livraison_livreur_id_8e4497a8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_livraison_livreur_id_8e4497a8 ON public.sales_livraison USING btree (livreur_id);


--
-- Name: sales_paiement_reference_transaction_bdc1ae9e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_paiement_reference_transaction_bdc1ae9e_like ON public.sales_paiement USING btree (reference_transaction varchar_pattern_ops);


--
-- Name: sales_recu_numero_7393a95a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_recu_numero_7393a95a_like ON public.sales_recu USING btree (numero varchar_pattern_ops);


--
-- Name: users_administrateur_cooperative_id_24e37cd6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_administrateur_cooperative_id_24e37cd6 ON public.users_administrateur USING btree (cooperative_id);


--
-- Name: users_membre_cooperative_id_661bc601; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_membre_cooperative_id_661bc601 ON public.users_membre USING btree (cooperative_id);


--
-- Name: users_utilisateur_email_d08b2a5d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_utilisateur_email_d08b2a5d_like ON public.users_utilisateur USING btree (email varchar_pattern_ops);


--
-- Name: users_utilisateur_groups_group_id_a71698e9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_utilisateur_groups_group_id_a71698e9 ON public.users_utilisateur_groups USING btree (group_id);


--
-- Name: users_utilisateur_groups_utilisateur_id_a9ec7e2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_utilisateur_groups_utilisateur_id_a9ec7e2b ON public.users_utilisateur_groups USING btree (utilisateur_id);


--
-- Name: users_utilisateur_user_permissions_permission_id_c32f2ac3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_utilisateur_user_permissions_permission_id_c32f2ac3 ON public.users_utilisateur_user_permissions USING btree (permission_id);


--
-- Name: users_utilisateur_user_permissions_utilisateur_id_fce4c46b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_utilisateur_user_permissions_utilisateur_id_fce4c46b ON public.users_utilisateur_user_permissions USING btree (utilisateur_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_utilisateur_id FOREIGN KEY (user_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: formation_formation formation_formation_formateur_id_1f68fbfc_fk_users_for; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_formation
    ADD CONSTRAINT formation_formation_formateur_id_1f68fbfc_fk_users_for FOREIGN KEY (formateur_id) REFERENCES public.users_formateur(utilisateur_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: formation_quiz formation_quiz_formation_id_1cc0355b_fk_formation_formation_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_quiz
    ADD CONSTRAINT formation_quiz_formation_id_1cc0355b_fk_formation_formation_id FOREIGN KEY (formation_id) REFERENCES public.formation_formation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: formation_suiviformation formation_suiviforma_formation_id_36d05635_fk_formation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_suiviformation
    ADD CONSTRAINT formation_suiviforma_formation_id_36d05635_fk_formation FOREIGN KEY (formation_id) REFERENCES public.formation_formation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: formation_suiviformation formation_suiviforma_membre_id_8a583b12_fk_users_mem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.formation_suiviformation
    ADD CONSTRAINT formation_suiviforma_membre_id_8a583b12_fk_users_mem FOREIGN KEY (membre_id) REFERENCES public.users_membre(utilisateur_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productions_cooperative productions_cooperat_createur_id_32e421e9_fk_users_mem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions_cooperative
    ADD CONSTRAINT productions_cooperat_createur_id_32e421e9_fk_users_mem FOREIGN KEY (createur_id) REFERENCES public.users_membre(utilisateur_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productions_production productions_producti_membre_id_70298c95_fk_users_mem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions_production
    ADD CONSTRAINT productions_producti_membre_id_70298c95_fk_users_mem FOREIGN KEY (membre_id) REFERENCES public.users_membre(utilisateur_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productions_produit productions_produit_production_id_3cf32b21_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions_produit
    ADD CONSTRAINT productions_produit_production_id_3cf32b21_fk_productio FOREIGN KEY (production_id) REFERENCES public.productions_production(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_commande sales_commande_acheteur_id_452d3519_fk_users_ach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commande
    ADD CONSTRAINT sales_commande_acheteur_id_452d3519_fk_users_ach FOREIGN KEY (acheteur_id) REFERENCES public.users_acheteur(utilisateur_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_lignecommande sales_lignecommande_commande_id_5ffb0313_fk_sales_commande_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_lignecommande
    ADD CONSTRAINT sales_lignecommande_commande_id_5ffb0313_fk_sales_commande_id FOREIGN KEY (commande_id) REFERENCES public.sales_commande(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_lignecommande sales_lignecommande_produit_id_780eeaac_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_lignecommande
    ADD CONSTRAINT sales_lignecommande_produit_id_780eeaac_fk_productio FOREIGN KEY (produit_id) REFERENCES public.productions_produit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_livraison sales_livraison_commande_id_cbf79e5a_fk_sales_commande_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_livraison
    ADD CONSTRAINT sales_livraison_commande_id_cbf79e5a_fk_sales_commande_id FOREIGN KEY (commande_id) REFERENCES public.sales_commande(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_livraison sales_livraison_livreur_id_8e4497a8_fk_users_liv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_livraison
    ADD CONSTRAINT sales_livraison_livreur_id_8e4497a8_fk_users_liv FOREIGN KEY (livreur_id) REFERENCES public.users_livreur(utilisateur_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_paiement sales_paiement_commande_id_a274bf4a_fk_sales_commande_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_paiement
    ADD CONSTRAINT sales_paiement_commande_id_a274bf4a_fk_sales_commande_id FOREIGN KEY (commande_id) REFERENCES public.sales_commande(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_recu sales_recu_paiement_id_99e42e09_fk_sales_paiement_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_recu
    ADD CONSTRAINT sales_recu_paiement_id_99e42e09_fk_sales_paiement_id FOREIGN KEY (paiement_id) REFERENCES public.sales_paiement(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_acheteur users_acheteur_utilisateur_id_58913aa9_fk_users_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_acheteur
    ADD CONSTRAINT users_acheteur_utilisateur_id_58913aa9_fk_users_utilisateur_id FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_administrateur users_administrateur_cooperative_id_24e37cd6_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_administrateur
    ADD CONSTRAINT users_administrateur_cooperative_id_24e37cd6_fk_productio FOREIGN KEY (cooperative_id) REFERENCES public.productions_cooperative(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_administrateur users_administrateur_utilisateur_id_f8d09738_fk_users_uti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_administrateur
    ADD CONSTRAINT users_administrateur_utilisateur_id_f8d09738_fk_users_uti FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_formateur users_formateur_utilisateur_id_039175fb_fk_users_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_formateur
    ADD CONSTRAINT users_formateur_utilisateur_id_039175fb_fk_users_utilisateur_id FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_livreur users_livreur_utilisateur_id_9af41ddc_fk_users_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_livreur
    ADD CONSTRAINT users_livreur_utilisateur_id_9af41ddc_fk_users_utilisateur_id FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_membre users_membre_cooperative_id_661bc601_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_membre
    ADD CONSTRAINT users_membre_cooperative_id_661bc601_fk_productio FOREIGN KEY (cooperative_id) REFERENCES public.productions_cooperative(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_membre users_membre_utilisateur_id_fb443556_fk_users_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_membre
    ADD CONSTRAINT users_membre_utilisateur_id_fb443556_fk_users_utilisateur_id FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_utilisateur_groups users_utilisateur_gr_utilisateur_id_a9ec7e2b_fk_users_uti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_groups
    ADD CONSTRAINT users_utilisateur_gr_utilisateur_id_a9ec7e2b_fk_users_uti FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_utilisateur_groups users_utilisateur_groups_group_id_a71698e9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_groups
    ADD CONSTRAINT users_utilisateur_groups_group_id_a71698e9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_utilisateur_user_permissions users_utilisateur_us_permission_id_c32f2ac3_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_user_permissions
    ADD CONSTRAINT users_utilisateur_us_permission_id_c32f2ac3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_utilisateur_user_permissions users_utilisateur_us_utilisateur_id_fce4c46b_fk_users_uti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_utilisateur_user_permissions
    ADD CONSTRAINT users_utilisateur_us_utilisateur_id_fce4c46b_fk_users_uti FOREIGN KEY (utilisateur_id) REFERENCES public.users_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


