"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uj#8l0^j^oabw#z)_hb85(uubrd39^0!_d2j-r3k+hxco0ei+a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,testserver'
).split(',')


# Application definition

INSTALLED_APPS = [
    # Thème d'administration moderne (doit précéder django.contrib.admin)
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # API
    'rest_framework',

    # Application ajouté
    'users',
    'formation',
    'productions',
    'sales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Connexion à la base de données.
# En production, la cible est PostgreSQL (cf. cahier des charges).
# Si les variables d'environnement PostgreSQL ne sont pas définies,
# l'application bascule automatiquement sur SQLite : elle fonctionne
# alors immédiatement, sans aucune installation de serveur de base.
if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Fichiers téléversés (images de produits, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modèle utilisateur personnalisé : c'est la table « utilisateur »
# décrite dans le cahier des charges qui sert de compte de connexion
# commun à tous les rôles (membre, admin, formateur, livreur, acheteur).
AUTH_USER_MODEL = 'users.Utilisateur'

# Pages web : redirections de connexion / déconnexion
LOGIN_URL = '/connexion/'
LOGIN_REDIRECT_URL = '/tableau-de-bord/'
LOGOUT_REDIRECT_URL = '/'

# Correspondance des messages Django avec les classes d'alerte Bootstrap
from django.contrib.messages import constants as messages_constants
MESSAGE_TAGS = {messages_constants.ERROR: 'danger'}

# Paiement MoneyFusion (FusionPay)
# URL d'API personnelle du marchand (tableau de bord MoneyFusion).
# Laissée vide -> mode simulation (paiement validé automatiquement),
# pratique en développement local.
MONEYFUSION_API_URL = os.getenv('MONEYFUSION_API_URL', '')
# Adresse publique du site (pour construire return_url / webhook_url).
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# Configuration de l'API REST :
# - Authentification par jeton JWT (Authorization: Bearer <token>)
# - Accès réservé par défaut aux utilisateurs authentifiés
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ============================================================
#  Interface d'administration (thème Jazzmin) — fluide & pro
# ============================================================
JAZZMIN_SETTINGS = {
    "site_title": "Administration",
    "site_header": "Coopératives Agricoles",
    "site_brand": "🌾 Coopératives",
    "welcome_sign": "Bienvenue dans l'administration",
    "copyright": "Coopératives Agricoles",
    "search_model": ["users.Utilisateur", "productions.Produit", "sales.Commande"],

    # Liens de la barre supérieure (permet de revenir au site)
    "topmenu_links": [
        {"name": "Retour au site", "url": "/", "new_window": False},
        {"name": "Tableau de bord", "url": "/tableau-de-bord/", "new_window": False},
        {"name": "Espace gestion", "url": "/gestion/", "new_window": False},
    ],
    # Liens du menu utilisateur (en haut à droite)
    "usermenu_links": [
        {"name": "Retour au site", "url": "/", "icon": "fas fa-arrow-left"},
    ],
    "navigation_expanded": True,

    # Menu latéral ordonné et regroupé
    "order_with_respect_to": [
        "users", "productions", "sales", "formation", "auth",
    ],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.Group": "fas fa-users-cog",
        "users.Utilisateur": "fas fa-user",
        "users.Membre": "fas fa-user-tractor",
        "users.Administrateur": "fas fa-user-tie",
        "users.Acheteur": "fas fa-user-tag",
        "users.Formateur": "fas fa-chalkboard-teacher",
        "users.Livreur": "fas fa-truck",
        "productions.Cooperative": "fas fa-warehouse",
        "productions.Production": "fas fa-seedling",
        "productions.Produit": "fas fa-box",
        "sales.Commande": "fas fa-shopping-cart",
        "sales.LigneCommande": "fas fa-list",
        "sales.Paiement": "fas fa-credit-card",
        "sales.Livraison": "fas fa-shipping-fast",
        "sales.Recu": "fas fa-receipt",
        "formation.Formation": "fas fa-graduation-cap",
        "formation.SuiviFormation": "fas fa-chart-line",
        "formation.Quiz": "fas fa-question-circle",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,  # édition en pleine page (enregistrement fiable)
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",              # thème clair et épuré
    "navbar": "navbar-success navbar-dark",
    "sidebar": "sidebar-dark-success",
    "accent": "accent-success",
    "brand_colour": "navbar-success",
    "sidebar_nav_compact_style": True,
    "actions_sticky_top": True,
}
