# Generated by Django 5.2.15 on 2026-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_contenu', models.CharField(choices=[('VIDEO', 'Vidéo'), ('COURS', 'Cours'), ('PDF', 'PDF'), ('QUIZ', 'Quiz')], default='COURS', max_length=20)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('duree_estimee', models.CharField(max_length=50)),
                ('statut', models.CharField(default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choix_a', models.CharField(max_length=255)),
                ('choix_b', models.CharField(max_length=255)),
                ('choix_c', models.CharField(max_length=255)),
                ('bonne_reponse', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score_quiz', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ABANDONNEE', 'Abandonnée')], default='EN_COURS', max_length=20)),
            ],
        ),
    ]
