# Generated by Django 6.0.6 on 2026-06-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_contenu', models.CharField(choices=[('VIDEO', 'Vidéo'), ('COURS', 'Cours'), ('PDF', 'PDF'), ('QUIZ', 'Quiz')], default='COURS', max_length=20)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_estimee', models.CharField()),
                ('statut', models.CharField(default='active', max_length=50)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score_quiz', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ABANDONNEE', 'Abandonnée')], default='EN_COURS', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membre')),
            ],
        ),
    ]
