# Generated by Django 6.0.6 on 2026-06-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='date_estimee',
            new_name='duree_estimee',
        ),
    ]
