# Generated by Django 5.2.15 on 2026-06-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formateur'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation'),
        ),
        migrations.AddField(
            model_name='suiviformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation'),
        ),
        migrations.AddField(
            model_name='suiviformation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membre'),
        ),
    ]
