# Generated by Django 6.0.6 on 2026-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_rename_date_estimee_formation_duree_estimee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='duree_estimee',
            field=models.CharField(max_length=50),
        ),
    ]
