# Generated by Django 6.0.6 on 2026-06-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_alter_formation_duree_estimee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choix_a', models.CharField(max_length=255)),
                ('choix_b', models.CharField(max_length=255)),
                ('choix_c', models.CharField(max_length=255)),
                ('bonne_reponse', models.CharField(max_length=1)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
    ]
