# Generated by Django 5.2.15 on 2026-06-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cooperative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("localisation", models.CharField(max_length=150)),
                ("date_creation", models.DateField(auto_now_add=True)),
                ("statut", models.CharField(default="active", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("type_culture", models.CharField(max_length=80)),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unite", models.CharField(max_length=30)),
                ("date_recolte", models.DateField()),
                ("statut_validation", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite_stock", models.IntegerField()),
                ("diponible", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/images/"
                    ),
                ),
            ],
        ),
    ]
