# Generated by Django 5.2.15 on 2026-06-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperative",
            name="createur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooperatives_creees",
                to="users.membre",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="membre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.membre"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productions.production"
            ),
        ),
    ]
