# Generated by Django 6.0.6 on 2026-06-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(default='en attente', max_length=50)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.acheteur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='en préparation', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(max_length=50)),
                ('statut', models.CharField(default='en attente', max_length=50)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.commande')),
            ],
        ),
    ]
