# Generated by Django 5.2.15 on 2026-06-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=30, unique=True)),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("statut", models.CharField(default="en attente", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sous_total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse_livraison", models.CharField(max_length=255)),
                ("date_livraison", models.DateTimeField(blank=True, null=True)),
                ("statut", models.CharField(default="en préparation", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("methode", models.CharField(max_length=50)),
                ("statut", models.CharField(default="en attente", max_length=50)),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_transaction",
                    models.CharField(max_length=100, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
